#docker-compose.yml included for future apache airflow update, and DBT.

services:
  agriflow-etl:
    image: fmahmud922/agriflow:lts
    env_file:
      - .env
    command: ["python3", "/AgriFlow.py"]
